ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - 1. བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མའི་འགྲེལ་པ་བྱང་ཆུབ་ལམ་གྱི་སྣང་བ་རབ་ཏུ་གསལ་བ།
  - 2. ལམ་གཙོ་རྣམ་གསུམ་གྱི་ཚིག་འགྲེལ་སྐལ་བཟང་ཐར་པའི་འཇུག་ངོགས།
  - 3. ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད་ལས་བློ་ལྡོག་རྣམ་བཞི་ཁོལ་དུ་ཕྱུང་བ།
  - 4. ཐེག་པ་ཆེན་པོའི་བློ་སྦྱོང་དོན་བདུན་མའི་ཁྲིད་ཡིག་བྱང་ཆུབ་གཞུང་ལམ།
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།
  sku: RDI-SS-05
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: The Collection of Treasured Practices of Mind Training and the Stages of the
      Path
    bo: ལམ་རིམ་དང་བློ་སྦྱོང་ཉམས་ལེན་གཅེས་བཏུས།
  collection:
    en: RDI Study Series–  Book 5
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༥
  author:
    en: Jamgon Kongtrul Lodro Thaye
    bo: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-05
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-05.epub
  description:
    en: ༄༅། །ས་གསུམ་གྱི་སྒྲོན་གཅིག་པུ་ཐུབ་པའི་གསུང་རབ་ཐམས་ཅད་ཀྱི་བཅུད་བསྡུས་པ། ཤིང་རྟ་ཆེན་པོ་གཉིས་ཀྱི་ལམ་སྲོལ།
      བརྒྱུད་པའི་ཆུ་བོ་གསུམ་འདྲེས་ཀྱི་མན་ངག མངོན་མཐོ་དང་ངེས་ལེགས་ཀྱི་ལམ་ཆེན། མདོ་དང་དགོངས་འགྲེལ་མཐའ་དག་གི་ལྡེ་མིག
      རྒྱ་བོད་མཁས་གྲུབ་ཐམས་ཅད་ཀྱི་གཤེགས་ཤུལ། སྐྱེས་བུ་གསུམ་གྱིས་ཉམས་སུ་བླང་བྱ་མ་ཚང་བ་མེད་པར་སྟོན་པའི་གཞུང་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ་ཞེས་བྱ་བ་སྟེ།
      མདོ་སྔགས་གཉིས་ཀའི་གནས་བསྡུས་པའི་བརྗོད་བྱ་ཡོངས་སུ་རྫོགས་པ་དང་། སེམས་ཅན་འདུལ་བའི་རིམ་པ་གཙོ་བོར་སྟོན་པའི་ལག་ཏུ་བླང་བདེ་བ།
      ཤང་རྟ་ཆེན་པོ་གཉིས་ཀྱི་ལུགས་ལ་མཁས་པའི་བླ་མ་གཉིས་ཀྱི་གདམས་པས་བརྒྱན་པས་ལུགས་གཞན་ལས་ཁྱད་དུ་འཕགས་པ་ཡིན་ནོ།
      །
    bo: ༄༅། །ས་གསུམ་གྱི་སྒྲོན་གཅིག་པུ་ཐུབ་པའི་གསུང་རབ་ཐམས་ཅད་ཀྱི་བཅུད་བསྡུས་པ། ཤིང་རྟ་ཆེན་པོ་གཉིས་ཀྱི་ལམ་སྲོལ།
      བརྒྱུད་པའི་ཆུ་བོ་གསུམ་འདྲེས་ཀྱི་མན་ངག མངོན་མཐོ་དང་ངེས་ལེགས་ཀྱི་ལམ་ཆེན། མདོ་དང་དགོངས་འགྲེལ་མཐའ་དག་གི་ལྡེ་མིག
      རྒྱ་བོད་མཁས་གྲུབ་ཐམས་ཅད་ཀྱི་གཤེགས་ཤུལ། སྐྱེས་བུ་གསུམ་གྱིས་ཉམས་སུ་བླང་བྱ་མ་ཚང་བ་མེད་པར་སྟོན་པའི་གཞུང་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ་ཞེས་བྱ་བ་སྟེ།
      མདོ་སྔགས་གཉིས་ཀའི་གནས་བསྡུས་པའི་བརྗོད་བྱ་ཡོངས་སུ་རྫོགས་པ་དང་། སེམས་ཅན་འདུལ་བའི་རིམ་པ་གཙོ་བོར་སྟོན་པའི་ལག་ཏུ་བླང་བདེ་བ།
      ཤང་རྟ་ཆེན་པོ་གཉིས་ཀྱི་ལུགས་ལ་མཁས་པའི་བླ་མ་གཉིས་ཀྱི་གདམས་པས་བརྒྱན་པས་ལུགས་གཞན་ལས་ཁྱད་དུ་འཕགས་པ་ཡིན་ནོ།
      །
